Burgers, Kuramoto Sivashinsky and Korteweg De Vries PDEs
Jacob-Stevens-Haas/gen-experiments pull request #8
Opened 2023-11-09 20:31 UTC by yb6599

I added implementations of Burgers 1D, Kuramoto Sivashinsky, and Korteweg De Vries PDEs. I can run experiments on Burgers and KS, although the coefficients are innacurate. Korteweg De Vries is stuck on gen_pde_data for a long time, so it does not work yet.

2023-11-10 16:07 UTC, Jacob-Stevens-Haas requested changes
Thanks for meeting Zach about this!  Try to provide a command line example of running these experiments, please.  Trying `diffuse1d` breaks for the reason mentioned below.

2023-11-10 16:07 UTC, Jacob-Stevens-Haas commented on src/gen_experiments/__init__.py
> +            "function_names": [lambda x: x, lambda x: x + x],
`mitosis` does not allow lambda functions in `Parameter` objects.  That was why we switched to `identity`.  Running experiments in this branch hits this error.

2023-11-10 16:07 UTC, Jacob-Stevens-Haas commented on src/gen_experiments/pdes.py
> +    # return np.reshape(-uxx-uxxxx-0.5*ux*ux)
Remove comment.

2023-11-10 16:09 UTC, Jacob-Stevens-Haas commented
Also see if KDV can work if you change the integration tolerances in `gen_pde_data`

2023-11-29 02:13 UTC, yb6599 commented
Hey Jake, the experiments for Burgers and Kuramoto Sivashinsky Equations should work now.
For Burgers, try `python -m gen_experiments burgers1D --seed 19 --param diff_params=test_axis --param feat_params=pde2 --param opt_params=test`
For KS, try `python -m gen_experiments ks --seed 19 --param diff_params=test_axis --param feat_params=pde2 --param opt_params=test`

2023-11-30 11:11 UTC, merged